export const sources = {
  vwap: {
    name: 'TradingView',
    title: 'Volume Weighted Average Price (VWAP)',
    url: 'https://www.tradingview.com/support/solutions/43000502018-volume-weighted-average-price-vwap/',
  },
  markets: {
    name: 'Investor.gov',
    title: 'How stock markets work',
    url: 'https://www.investor.gov/introduction-investing/investing-basics/how-stock-markets-work',
  },
  orders: {
    name: 'Investor.gov',
    title: 'Types of orders',
    url: 'https://www.investor.gov/introduction-investing/investing-basics/how-stock-markets-work/types-orders',
  },
  execution: {
    name: 'Investor.gov',
    title: 'Executing an order',
    url: 'https://www.investor.gov/introduction-investing/investing-basics/how-stock-markets-work/executing-order',
  },
  stocks: {
    name: 'Investor.gov',
    title: 'Stocks: ownership, returns, and risk',
    url: 'https://www.investor.gov/introduction-investing/investing-basics/investment-products/stocks',
  },
  crypto: {
    name: 'Investor.gov',
    title: 'Crypto assets: investor education',
    url: 'https://www.investor.gov/additional-resources/spotlight/crypto-assets',
  },
  day: {
    name: 'FINRA',
    title: 'Day trading and its risks',
    url: 'https://www.finra.org/investors/investing/investment-products/stocks/day-trading',
  },
  futures: {
    name: 'CME Group',
    title: 'Definition of a futures contract',
    url: 'https://www.cmegroup.com/education/courses/introduction-to-futures/definition-of-a-futures-contract',
  },
  margin: {
    name: 'CME Group',
    title: 'Understanding margin changes',
    url: 'https://www.cmegroup.com/education/articles-and-reports/understanding-margin-changes',
  },
  risk: {
    name: 'CME Group',
    title: 'Position and risk management',
    url: 'https://www.cmegroup.com/education/courses/things-to-know-before-trading-cme-futures/position-and-risk-management',
  },
  plan: {
    name: 'CME Group',
    title: 'Risk management and your trade plan',
    url: 'https://www.cmegroup.com/education/courses/building-a-trade-plan/risk-management-and-your-trade-plan',
  },
  charts: {
    name: 'CME Group',
    title: 'Technical analysis course',
    url: 'https://www.cmegroup.com/education/courses/technical-analysis',
  },
  support: {
    name: 'CME Group',
    title: 'Support and resistance',
    url: 'https://www.cmegroup.com/education/courses/technical-analysis/support-and-resistance',
  },
  indicators: {
    name: 'Fidelity',
    title: 'Technical indicator guide',
    url: 'https://www.fidelity.com/learning-center/trading-investing/technical-analysis/technical-indicator-guide',
  },
  rsi: {
    name: 'Fidelity',
    title: 'Relative Strength Index (RSI)',
    url: 'https://www.fidelity.com/learning-center/trading-investing/technical-analysis/technical-indicator-guide/rsi',
  },
  macd: {
    name: 'Fidelity',
    title: 'Moving Average Convergence/Divergence',
    url: 'https://www.fidelity.com/learning-center/trading-investing/technical-analysis/technical-indicator-guide/macd',
  },
  atr: {
    name: 'Fidelity',
    title: 'Average True Range',
    url: 'https://www.fidelity.com/learning-center/trading-investing/technical-analysis/technical-indicator-guide/atr',
  },
  bands: {
    name: 'Fidelity',
    title: 'Bollinger Bands',
    url: 'https://www.fidelity.com/learning-center/trading-investing/technical-analysis/technical-indicator-guide/bollinger-bands',
  },
  bias: {
    name: 'Fidelity',
    title: 'Investing biases',
    url: 'https://www.fidelity.com/learning-center/wealth-management-insights/investing-biases',
  },
  emotion: {
    name: 'Fidelity',
    title: 'The market cycle and investors',
    url: 'https://www.fidelity.com/viewpoints/investing-ideas/the-market-cycle-and-investors',
  },
  pitfalls: {
    name: 'Fidelity',
    title: 'Investors’ biggest pitfalls',
    url: 'https://www.fidelity.com/viewpoints/personal-finance/financial-improvement',
  },
};
export type SourceKey = keyof typeof sources;
export const phases = [
  {
    id: 0,
    title: 'The mindset',
    description: 'Start with perspective. Understand the game before you play it.',
    tag: 'Build your foundation',
    art: 'steps',
  },
  {
    id: 1,
    title: 'Market fundamentals',
    description: 'The mechanics behind every order, price, and trade.',
    tag: 'Learn the language',
    art: 'globe',
  },
  {
    id: 2,
    title: 'Reading charts',
    description: 'Turn a screen full of candles into a story you understand.',
    tag: 'See the bigger picture',
    art: 'candles',
  },
  {
    id: 3,
    title: 'Why price moves',
    description: 'Explore supply, demand, and the people behind the price.',
    tag: 'Look beneath the surface',
    art: 'waves',
  },
  {
    id: 4,
    title: 'Technical analysis',
    description: 'Build a small, useful toolkit. Know its limitations.',
    tag: 'Find your tools',
    art: 'candles',
  },
  {
    id: 5,
    title: 'Risk management',
    description: 'Learn to protect your capital before chasing a return.',
    tag: 'Stay in the game',
    art: 'shield',
  },
  {
    id: 6,
    title: 'Trading psychology',
    description: 'Make a plan for the person making the decisions: you.',
    tag: 'Build better habits',
    art: 'steps',
  },
];
type LessonRow = [
  title: string,
  explanation: string,
  example: string,
  takeaway: string,
  practice: string,
  source: SourceKey,
];
const content: LessonRow[][] = [
  [
    [
      'What is a market?',
      'A market is a place where buyers and sellers exchange something of value. It can be a fruit stall, a stock exchange, or an online platform. In financial markets, that “something” might be a share in a company, a currency, or a contract. A trade happens when a buyer and a seller agree on a price. The price you see on a screen usually reflects the most recent trade—not a promise about the next one.',
      'Imagine a weekend bicycle market. A seller asks $120 for a used bike. You offer $100. Nothing happens until one of you accepts a price. You agree on $110, and a trade happens. Financial markets do something similar, often matching thousands of orders electronically.',
      'A price is an agreement between two sides at a moment in time. It is not a guarantee of what an asset is worth tomorrow.',
      'Think of something you bought recently. Who was the buyer, who was the seller, and what made you agree on the price?',
      'markets',
    ],
    [
      'Why do prices move?',
      'Prices change as people revise what they are willing to pay or accept. News, expectations, urgency, and available orders all matter. Every completed trade has both a buyer and a seller; rising prices do not literally mean more buyers than sellers in those trades.',
      'A concert has only ten resale tickets at $50. Eager buyers take them, then accept the next sellers’ $60 prices. The latest transaction price rises.',
      'Look at willingness to trade at each price, not just a head count of buyers and sellers.',
      'What might happen if the next ticket seller only accepts $70, but nobody is willing to pay it?',
      'execution',
    ],
    [
      'Who are buyers and sellers?',
      'Individuals, investment funds, businesses, and market makers all trade. They have different time horizons and reasons: investing, reducing an existing risk, or speculating on a price move. The person on the other side does not need to share your goal.',
      'A farmer sells a crop futures contract to reduce price uncertainty. A trader buys it to take price risk. The same transaction can serve two different purposes.',
      'You can observe a trade, but you usually cannot know the participants’ full intentions.',
      'Write two possible reasons for selling an asset besides believing its price will fall.',
      'futures',
    ],
    [
      'Why could Bitcoin move from $50k to $70k?',
      'This is a hypothetical move, not a forecast. Changing expectations, available supply for sale, capital flows, and leverage can all affect Bitcoin prices. A price chart alone cannot isolate which cause mattered most. Crypto also brings custody and platform risks.',
      'A move from $50,000 to $70,000 is a 40% increase: $20,000 divided by $50,000. Buying 0.01 BTC would cost $500 and later be worth $700, before fees. The move could also go the other way.',
      'A compelling story about a price move is not proof of its cause or a reliable forecast.',
      'Calculate the percentage fall from $70,000 back to $50,000. Why is it about 28.6%, rather than 40%?',
      'crypto',
    ],
    [
      'Who actually makes money?',
      'An investor may earn dividends or sell an asset for more than its cost. A trader needs gains to exceed losses and trading costs over time. Brokers and exchanges may earn fees regardless of whether a customer’s trade succeeds. None of these roles has guaranteed profits.',
      'You gain $30 on a trade but pay $4 in total fees and $2 through unfavorable execution. Your net gain is $24, before any tax.',
      'Measure results after costs. A screenshot of one winning trade says little about long-term performance.',
      'A second trade loses $25 after costs. What is the combined result of the two trades?',
      'stocks',
    ],
    [
      'Why do so many traders lose?',
      'There is no universal, verified “90% of all traders lose” statistic. Results depend on the market, product, study period, and population. Frequent costs, excessive leverage, poor risk limits, and competition can make short-term trading difficult.',
      'Ten trades each make $1 before costs. If each round trip costs $1.50, the total result is a $5 loss—even though every trade looked profitable before fees.',
      'Evaluate specific evidence. Treat both easy-profit promises and sweeping loss statistics with skepticism.',
      'List three costs or risks that a social media profit screenshot might leave out.',
      'day',
    ],
    [
      'Investing, swing trading, day trading & scalping',
      'Investing usually looks years ahead. Swing trading typically holds positions for days or weeks. Day trading opens and closes positions within a day; scalping seeks very small moves over seconds or minutes. These are common descriptions, not universal legal definitions.',
      'Maya buys a diversified fund for a ten-year goal. Ali holds a share for a week. Sam closes a position before the session ends. Their time horizons create different demands and risks.',
      'Shorter holding periods usually demand more attention to execution and transaction costs.',
      'Compare the time commitment, overnight exposure, and costs of two of these styles.',
      'day',
    ],
    [
      'Which style fits your life?',
      'Start with your schedule, financial resilience, goals, and tolerance for uncertainty. A style that requires constant monitoring may conflict with a full-time job. Personality alone does not establish suitability or an edge. Choosing not to trade is also a valid decision.',
      'Noor can study for 20 minutes after work but cannot watch markets during the day. She first uses a simulated journal to learn, instead of forcing a screen-intensive routine.',
      'Choose a sustainable learning routine before choosing a trading identity.',
      'Write down when you can study, what you want to learn, and which money must remain untouched.',
      'plan',
    ],
  ],
  [
    [
      'Spot markets',
      'A spot transaction buys or sells an asset at a current agreed price for near-term settlement. Settlement timing depends on the asset and venue. Owning spot assets without borrowing differs from holding a leveraged derivative.',
      'You pay $200 to buy two shares at $100 each. If the price drops to $90, their value is $180 before costs. You still own two shares.',
      '“Spot” does not mean instant settlement, no fees, or no risk.',
      'Compare owning an asset with agreeing to a future contract based on its price.',
      'stocks',
    ],
    [
      'Futures',
      'A futures contract is a standardized exchange-traded agreement with defined terms for a future date. It may settle in cash or through delivery. Price exposure depends on the contract multiplier, not just the margin deposited. Perpetual crypto contracts are different products.',
      'In a hypothetical contract worth $5 per point, a 20-point price change produces a $100 gain or loss per contract. The margin deposit is not the contract’s full value.',
      'Read the multiplier, settlement terms, expiry, and margin rules before interpreting a futures price.',
      'What would a 20-point adverse move cost with three of these hypothetical contracts?',
      'futures',
    ],
    [
      'Margin',
      'In securities accounts, margin often means borrowing from a broker. In futures, margin is collateral supporting a contract rather than a down payment on the asset. Requirements can change, and a broker may close positions when collateral becomes insufficient.',
      'A hypothetical futures position needs $1,000 in collateral. After a $300 loss, only $700 remains. A higher maintenance requirement could trigger a demand for funds or liquidation.',
      'Margin is not a maximum-loss limit. Losses can exceed the initial deposit.',
      'Explain why having enough margin to open a position does not mean you can afford its risk.',
      'margin',
    ],
    [
      'Leverage',
      'Leverage gives you exposure larger than your own capital. It magnifies percentage gains and losses on that capital. Financing, funding, fees, and liquidation rules can make the real outcome worse than a simple price calculation.',
      'With $100 supporting $1,000 of exposure, a 5% adverse price move loses $50 before costs—half the original capital. Liquidation can happen before all capital is lost.',
      'Always calculate exposure and loss in currency, not only the advertised leverage multiple.',
      'At the same exposure, what does a 2% adverse move do to the $100 capital?',
      'risk',
    ],
    [
      'Going long',
      'A long position generally benefits when its price rises and loses when it falls. Buying an asset outright is one way to be long; using a derivative adds contract-specific risks. An unrealized gain is a change in value before closing the position.',
      'Buy three shares at $40 and sell at $44. The gross gain is 3 × $4 = $12. If you sell at $36 instead, the gross loss is $12.',
      '“Long” describes the direction of your exposure, not how long you hold it.',
      'Work out the gross result if those shares are sold at $41.50.',
      'stocks',
    ],
    [
      'Going short',
      'Short selling a stock generally involves borrowing shares, selling them, and later buying them back. Borrow fees, recalls, and margin matter. A stock price can rise without a fixed ceiling, so short-sale losses are theoretically unlimited. Futures shorts have different mechanics.',
      'Borrow and sell one share for $50, then buy it back for $40: gross gain $10. If you must buy it back at $80, the gross loss is $30, before costs.',
      'A short position can lose far more than the amount you hoped to gain.',
      'Why is a 100% price rise especially dangerous to someone short?',
      'day',
    ],
    [
      'Liquidity',
      'Liquidity is how easily you can trade a useful quantity without moving the price much. A tight spread helps, but depth and changing conditions also matter. A market that appears liquid can become thin during stress.',
      'A shop with a warehouse of apples can fill a large order at its displayed price. A stall with only two apples may need a higher price to supply the rest. Order books behave similarly.',
      'Check available quantity as well as the quoted price.',
      'Why might a large market order receive several different execution prices?',
      'execution',
    ],
    [
      'Market makers',
      'Market makers quote prices at which they are willing to buy and sell. They help other participants transact and manage the risk of inventory they hold. The spread can contribute to revenue but is not guaranteed profit.',
      'A dealer bids $99 and offers $101. Buying and later selling one unit at those prices yields a $2 gross spread. A sudden price drop while holding inventory can wipe that out.',
      'Providing liquidity is a business with inventory and execution risks.',
      'Describe one way a market maker could lose money despite quoting a spread.',
      'execution',
    ],
    [
      'The order book',
      'An order book shows displayed buy and sell orders at different prices on a venue. It is a changing snapshot, not a complete map of everyone’s intentions. Orders can be canceled, and some liquidity is not displayed.',
      'There are two units offered at $100 and three at $101. A market buy for four units could fill two at each price, averaging $100.50, if the book stays unchanged.',
      'Visible orders are not promises that liquidity will remain available.',
      'Calculate the average fill for five units in the same hypothetical book.',
      'orders',
    ],
    [
      'The bid',
      'The best bid is the highest displayed price a buyer currently offers on a venue. A small market sell may execute there, but quantity and market changes affect the fill. A quoted bid is not the same as the latest trade.',
      'The best bid is $49.90 for ten shares. Selling five may fill at $49.90. Selling fifty could consume lower bids too.',
      'The bid helps describe what you might receive when selling immediately.',
      'If the bid is $49.90 and the ask is $50.10, which quote is relevant to an immediate sale?',
      'orders',
    ],
    [
      'The ask',
      'The best ask, also called the offer, is the lowest displayed price a seller currently accepts on a venue. An immediate purchase generally trades against offers, subject to available quantity and changing prices.',
      'A shop offers one item for $20. Your willingness to pay $19 does not create a sale until a seller accepts it. Buying immediately means accepting an available offer.',
      'The ask helps describe what you might pay when buying immediately.',
      'Explain why a limit buy below the best ask might remain unfilled.',
      'orders',
    ],
    [
      'The spread',
      'The bid–ask spread is the difference between the best ask and best bid. It is one part of trading friction, alongside fees and price impact. A narrow spread in dollars can still be large relative to a low-priced asset.',
      'With a bid of $99 and ask of $101, buying then immediately selling one unit at unchanged quotes loses $2 before fees. That $2 is the spread.',
      'Small costs matter when repeated across many trades.',
      'What would the same immediate round trip cost for twenty units?',
      'execution',
    ],
  ],
  [
    [
      'Candlesticks',
      'A candle summarizes the open, high, low, and close for one interval. Its body connects open and close; its wicks extend to the high and low. Colors are configurable, so read the values rather than relying on color alone.',
      'A candle opens at $100, reaches $108, dips to $97, and closes at $105. Its body runs from $100 to $105; wicks reach $97 and $108.',
      'One candle summarizes a period. It does not reveal the exact sequence of every trade.',
      'Sketch that candle and label all four prices.',
      'charts',
    ],
    [
      'Timeframes',
      'A timeframe sets the duration summarized by each candle. A five-minute chart and a daily chart describe the same market at different scales. A short-term rise can exist inside a longer decline.',
      'A share rises from $90 to $92 during an hour but is still below last week’s $100. The hourly move is up; the broader context may still be down.',
      'Always name the timeframe when describing a trend.',
      'How many five-minute intervals fit in one hour?',
      'charts',
    ],
    [
      'Market structure',
      'Market structure, in chart reading, describes the sequence of swing highs and lows. Traders use it to label trends or ranges. Selecting meaningful swings is partly subjective and depends on scale.',
      'A price path goes 100 → 110 → 104 → 116 → 109. Peaks and pullbacks have moved higher. That describes the observed path; it does not guarantee the next peak.',
      'Use structure as a description first, then test any trading rules separately.',
      'Identify the two peaks and two pullback lows in the example.',
      'charts',
    ],
    [
      'Trends',
      'An uptrend generally contains rising swing highs and lows; a downtrend has falling ones. A range lacks a sustained direction. Trends are clearer in hindsight, and rules for detecting them can give false signals.',
      'Walking uphill still includes small downward steps. Likewise, a price can pull back inside an uptrend without every decline marking a reversal.',
      'A trend is a pattern across observations, not one rising or falling candle.',
      'Find an imaginary price sequence that moves sideways rather than trending.',
      'charts',
    ],
    [
      'Higher highs',
      'A higher high is a swing peak above a previous comparable peak. It suggests price has reached new ground on that timeframe. It can be a temporary spike rather than a durable trend.',
      'Price peaks at $105, retreats, then reaches $109. The second peak is a higher high. A later close back at $103 would add different context.',
      'Compare like-for-like swings and keep track of what happens after the new high.',
      'Write a price sequence containing two higher highs.',
      'charts',
    ],
    [
      'Higher lows',
      'A higher low is a pullback low above a previous comparable low. Together with higher highs, it can describe an uptrend. A low is only confirmed under your chosen observation rule after price moves away.',
      'A first pullback ends at $98 and the next at $102. The second low is higher even though price fell while forming it.',
      'A pullback can be a decline locally and still preserve a broader rising structure.',
      'Pair these lows with peaks that would describe an uptrend.',
      'charts',
    ],
    [
      'Lower highs',
      'A lower high is a rebound peak below a previous comparable peak. It can appear within a downtrend, but a single lower high does not establish what price will do next.',
      'Price rebounds to $120, falls, then only reaches $115 on the next rebound. Buyers have not returned price to the previous peak.',
      'A rising move is not automatically an uptrend; compare it with earlier swings.',
      'Add two swing lows to the example to create a falling structure.',
      'charts',
    ],
    [
      'Lower lows',
      'A lower low is a swing trough below a previous comparable trough. A sequence of lower lows and lower highs describes falling structure on the chosen timeframe.',
      'A price bottoms at $80, rebounds to $86, then falls to $76. The second trough is a lower low. It says where price has been, not how far it must fall.',
      'Descriptions of past structure are not guarantees of continuation.',
      'Explain the difference between one red candle and a sequence of lower lows.',
      'charts',
    ],
  ],
  [
    [
      'Supply and demand',
      'Supply describes quantities sellers are willing to offer at different prices; demand describes quantities buyers are willing to purchase. New information can change both. A chart zone labeled “demand” is an interpretation, not a visible queue of guaranteed buyers.',
      'Rain reduces a farmer’s strawberry supply while shoppers still want the same amount. Prices may rise. If shoppers switch to another fruit, the outcome can change.',
      'Prices depend on both sides and their alternatives.',
      'Name a change that could lower demand even when supply stays unchanged.',
      'markets',
    ],
    [
      'Liquidity and price moves',
      'Thin available orders can let a modest trade move the quoted price a lot. Deep markets can absorb more quantity, though liquidity changes over time. Trading volume measures completed transactions, not all currently available liquidity.',
      'One buyer takes the only unit offered at $10. The next available offer is $12. The quote jumps even though just one unit traded.',
      'A large price move does not always mean a large amount of money traded.',
      'Explain why yesterday’s high volume does not guarantee liquidity right now.',
      'execution',
    ],
    [
      'Stop orders and “stop hunts”',
      'Stops can cluster around obvious levels. When triggered, stop-market orders may add buying or selling pressure. A quick move through a level does not prove deliberate manipulation; ordinary volatility or thin liquidity can produce similar price action.',
      'Many hypothetical sell stops sit below $100. Price touches $99.90, activating market sells. Some fill below the stop price, and price may later recover.',
      'A wick alone cannot tell you who acted or why. Stop prices do not guarantee execution prices.',
      'Give two explanations for a brief dip below a previous low.',
      'orders',
    ],
    [
      'Breakouts',
      'A breakout is a move beyond a previously identified range or level. Traders use different confirmation rules, such as a close beyond the level. A breakout is an observation, not proof that momentum will continue.',
      'An asset has traded between $45 and $50. It closes at $51. That meets a “close above $50” rule, but the next session could return inside the range.',
      'Define the level and confirmation rule before looking at the outcome.',
      'Write one objective rule for identifying a breakout in a paper journal.',
      'support',
    ],
    [
      'False breakouts',
      'A false breakout moves past a level and then returns. The label is usually assigned after the reversal. It illustrates why entry ideas need a plan for being wrong.',
      'Price crosses a $30 ceiling, reaches $31, then closes at $29. A buyer who assumed the level guaranteed further gains now faces a loss.',
      'No confirmation method eliminates failed signals.',
      'How would fees and slippage affect a plan that repeatedly trades small breakouts?',
      'support',
    ],
    [
      'Accumulation',
      'Accumulation can mean building a position over time. In chart narratives, it often describes a range interpreted as quiet buying. Public candles alone cannot confirm that a specific institution is accumulating.',
      'A fund hypothetically buys 1,000 shares in small installments over a week to manage execution. A chart might look sideways, but sideways prices can have other causes.',
      'Separate evidence of transactions from a story about hidden buyers.',
      'What additional evidence would you want before calling a range “institutional accumulation”?',
      'execution',
    ],
    [
      'Distribution',
      'Distribution can mean gradually reducing holdings. Chart traders sometimes use the label for a range they think precedes a decline. The same pattern can appear without coordinated selling and can resolve upward.',
      'An investor sells part of a long-held position in several batches to rebalance. This does not necessarily mean they predict a crash.',
      'Selling can reflect portfolio needs rather than a bearish forecast.',
      'Write two non-predictive reasons someone might reduce a position.',
      'stocks',
    ],
    [
      'Institutional buying',
      'Funds, pensions, and other large organizations can trade significant quantities. They may split orders, rebalance, or hedge. Their size does not mean they know the future, and delayed public disclosures may not represent current holdings.',
      'A fund receives new deposits and buys shares to maintain its existing allocation. The purchase can be driven by cash flows rather than a new prediction.',
      'A large trade is evidence of activity, not automatic evidence of superior information.',
      'Why might copying a delayed holdings report produce a different result?',
      'execution',
    ],
    [
      'Retail psychology',
      'Individual traders may respond to social proof, recent wins, or fear of missing out. Institutions can also exhibit biases. Crowd behavior is context, not a reliable timer for market tops and bottoms.',
      'A group chat celebrates an asset after a sharp rise. You feel pressure to buy even though you have not written an exit or risk plan.',
      'Popularity is not a substitute for evaluating a decision.',
      'Write one question you would ask before acting on a popular trading story.',
      'bias',
    ],
  ],
  [
    [
      'Support & resistance',
      'Support is an area where declines previously met buying interest; resistance is an area where advances met selling. Treat them as zones to investigate, not walls that cannot break.',
      'A price rebounds near $20 several times, then later trades at $18. The earlier reactions made $20 a useful reference, not a guaranteed floor.',
      'A past reaction does not obligate future buyers or sellers to act again.',
      'Mark a hypothetical zone and define what would show it has failed.',
      'support',
    ],
    [
      'Trendlines',
      'A trendline connects selected swing points to help visualize direction. Its position depends on which points you choose and the chart scale. It can organize observations without being a predictive law.',
      'Connect lows at $40, $43, and $46 across equally spaced dates. A later price below the line changes that picture but does not alone establish a new trend.',
      'Do not keep redrawing a line just to make every outcome look correct.',
      'Decide in advance whether your line uses closing prices or intraperiod extremes.',
      'charts',
    ],
    [
      'Channels',
      'A channel uses roughly parallel boundaries to describe a price path. The upper and lower edges are estimates. A market can overshoot a boundary or leave the channel entirely.',
      'A series of swings rises between two sloping lines. A move to the upper edge describes location within the pattern; it is not an automatic sell instruction.',
      'A neat drawing can hide uncertainty in the underlying pattern.',
      'Describe how you would recognize that a channel no longer fits.',
      'charts',
    ],
    [
      'Moving averages',
      'A simple moving average is the arithmetic mean of a chosen number of recent prices. It smooths fluctuations and lags new information. An exponential average weights recent values more heavily.',
      'Closes of $10, $12, and $14 give a three-period simple average of $12. If the next close is $16, the new average uses $12, $14, and $16, giving $14.',
      'An average summarizes the past. Its slope is not a promise about the future.',
      'Calculate the three-period average after a new close of $9.',
      'indicators',
    ],
    [
      'Volume',
      'Volume counts how much traded over a specified period and venue. High volume signals activity but does not by itself tell you whether the next move is up or down. Crypto volume can vary substantially across venues.',
      'A share trades 100,000 units today versus 20,000 yesterday. Participation increased. Every completed unit still had both a buyer and seller.',
      'Compare like periods and venues, and interpret volume alongside price.',
      'Why is comparing a full day’s volume with the first ten minutes misleading?',
      'indicators',
    ],
    [
      'RSI',
      'The Relative Strength Index measures momentum on a scale from 0 to 100 using recent gains and losses. Levels around 70 and 30 are common reference points. Strong trends can keep RSI elevated or depressed for extended periods.',
      'RSI reaches 75 while price keeps climbing. “Overbought” describes the indicator’s reading; it does not force price to reverse.',
      'Do not turn an RSI threshold into an automatic prediction.',
      'What could go wrong with selling every time RSI rises above 70?',
      'rsi',
    ],
    [
      'MACD',
      'MACD compares a faster and slower exponential moving average. Common settings use 12 and 26 periods, plus a nine-period signal average. Crossovers can help describe momentum changes, but lag and repeated false signals are possible.',
      'Price oscillates sideways. The MACD and signal lines cross several times, producing contradictory signals while trading costs accumulate.',
      'An indicator can be mathematically precise and still be unreliable as a standalone trade signal.',
      'Why might a trend-following indicator struggle in a sideways market?',
      'macd',
    ],
    [
      'ATR',
      'Average True Range summarizes price-range volatility. True range accounts for the current high and low and gaps from the previous close. ATR measures size of movement, not direction.',
      'An asset with ATR of $3 has recently had larger true ranges than when its ATR was $1. It could still move more or less than $3 in the next period.',
      'ATR is a historical volatility estimate, not a guaranteed daily boundary.',
      'If volatility doubles, why might keeping the same position size increase risk?',
      'atr',
    ],
    [
      'VWAP',
      'Volume-weighted average price weights transaction prices by their traded quantities, often within one session. It is an execution benchmark. Charting platforms may approximate it from candle data, and the reset period matters.',
      'Ten units trade at $100 and thirty at $102. VWAP is (10 × 100 + 30 × 102) ÷ 40 = $101.50.',
      'Price above or below VWAP describes relative location; it does not guarantee a return to the average.',
      'Calculate VWAP for ten units at $20 and ten units at $24.',
      'vwap',
    ],
    [
      'Bollinger Bands',
      'Bollinger Bands place a moving average between upper and lower bands based on a multiple of standard deviation. A common setup uses 20 periods and two standard deviations. Band width changes with recent variability.',
      'Price repeatedly touches the upper band during a strong rise. Selling each touch assumes reversals that may not occur.',
      'A band touch is context, not an automatic reversal signal; bands are not guaranteed probability limits.',
      'What might narrower bands tell you about recent variability—and what can they not tell you?',
      'bands',
    ],
  ],
  [
    [
      'Position sizing',
      'For a simple unleveraged position, planned quantity equals the loss budget divided by the distance from entry to a planned exit. Round down when whole units are required. Fees, gaps, and slippage can make realized losses larger.',
      'In a hypothetical $1,000 practice account, a $10 loss budget and $2 entry-to-stop distance allow five shares before costs. That is an illustration, not a recommended risk level.',
      'Start with what the trade could lose, then calculate quantity.',
      'If the stop distance increases to $5 with the same budget, what quantity fits?',
      'risk',
    ],
    [
      'Risk / reward',
      'A planned risk-to-reward ratio compares the potential loss with the target gain. Here, 1:2 means risking $1 to target $2. It says nothing by itself about how likely either outcome is.',
      'An entry at $50, planned exit at $48, and target at $54 imply $2 risk and $4 reward per share before costs: 1:2. Neither exit price is guaranteed.',
      'A large target does not create an edge merely because it looks attractive on paper.',
      'What is the planned ratio with $3 risk and a $6 target?',
      'plan',
    ],
    [
      'Win rate',
      'Win rate is winning trades divided by total closed trades in a defined sample. It omits the size of gains and losses. Small samples can be misleading, and break-even trades need a consistent counting rule.',
      'Eight wins of $5 and two losses of $30 produce an 80% win rate but a $20 net loss before costs.',
      'A high win rate can coexist with losing money.',
      'Calculate the result of four $20 wins and six $10 losses.',
      'plan',
    ],
    [
      'Expected value',
      'A simplified estimate per trade is win probability × average win minus loss probability × average loss, then minus costs. Use consistent definitions and avoid subtracting costs twice. Historical estimates have uncertainty and may not persist.',
      'A hypothetical 40% win rate, $30 average gross win, $10 average gross loss, and $1 average cost give 0.4 × 30 − 0.6 × 10 − 1 = $5 per trade.',
      'Positive estimated expectancy is not a guarantee; outcomes can cluster into losing streaks.',
      'Recalculate the example if the average gross win falls to $15.',
      'risk',
    ],
    [
      'Drawdown',
      'Drawdown is the decline from a previous account peak to a later value. Percentage drawdown uses the peak as its base. Recovering a loss requires a larger percentage gain because the remaining base is smaller.',
      'An account falls from $1,000 to $800: a 20% drawdown. Returning to $1,000 requires a $200 gain on $800, which is 25%.',
      'Losses and recovery gains are not symmetric percentages.',
      'What gain is needed to recover after a 50% drawdown?',
      'risk',
    ],
    [
      'Compounding',
      'Compounding means future returns apply to a changing balance. Losses compound too. Constant-return projections are arithmetic scenarios, not realistic promises of smooth trading performance.',
      'A $100 balance gains 10% to reach $110, then loses 10% to reach $99. Equal percentage gains and losses do not cancel.',
      'Be skeptical of calculators that assume you can repeat a daily trading return indefinitely.',
      'Calculate two consecutive 10% losses starting from $100.',
      'stocks',
    ],
    [
      'Account survival',
      'Survival means keeping losses and commitments within limits you can sustain. Consider combined exposure, correlated positions, costs, gaps, and money needed outside trading. A daily stop rule can guide behavior but cannot guarantee a maximum market loss.',
      'Three positions each plan to risk $10, but all depend on the same market move. They may lose together, and a gap could make the total exceed $30.',
      'Risk is a portfolio question as well as a single-trade question.',
      'Draft a paper-trading rule for when you stop and review your decisions.',
      'plan',
    ],
  ],
  [
    [
      'Fear',
      'Fear can make a person freeze, exit impulsively, or avoid reviewing losses. The goal is to notice the feeling and use a prepared process. Emotional comfort does not make a trade safe, and discomfort does not prove it is wrong.',
      'In a simulation, a small decline makes you abandon a plan immediately. Record the trigger and whether the original assumptions actually changed.',
      'Use a journal to separate what happened from what you felt.',
      'Write one physical or mental sign that tells you to pause.',
      'bias',
    ],
    [
      'Greed',
      'Wanting a larger gain can tempt you to abandon a risk limit or move a target without a reason. Rules can be revised when evidence changes, but an emotional urge is different from a tested revision.',
      'After a simulated win, you double the next position just because you feel confident. The new size changes the risk even if the setup looks similar.',
      'Review changes to size and exits deliberately, rather than in the excitement of a result.',
      'Write a reason to change a plan that is based on evidence rather than excitement.',
      'emotion',
    ],
    [
      'FOMO',
      'Fear of missing out can make urgency feel like evidence. Social feeds highlight selected successes and omit many failures. Missing a move does not create a debt that the next trade must repay.',
      'An asset jumps while you are offline. You consider buying immediately because friends are celebrating, despite having no entry criteria or exit plan.',
      'An opportunity you do not understand is something you can let pass.',
      'Write a short pause checklist for the next time a popular trade feels urgent.',
      'bias',
    ],
    [
      'Revenge trading',
      'Revenge trading describes taking new risks primarily to recover a recent loss. The market does not respond to your need to break even. A predefined pause and review can interrupt an escalating sequence.',
      'After losing $20 in a simulation, you risk $60 on an unplanned trade to “win it back.” The second decision should be evaluated independently of the first loss.',
      'A previous loss is not a reason for the next position to be larger.',
      'Draft a rule for what you do immediately after an emotionally difficult loss.',
      'pitfalls',
    ],
    [
      'Overtrading',
      'Overtrading means taking more activity or exposure than your process justifies. It can come from boredom, urgency, or chasing losses. Additional trades also create additional opportunities for costs and mistakes.',
      'Your paper plan identifies two qualifying setups, but you take ten because the afternoon feels slow. Eight decisions lack the reason your process required.',
      'Doing nothing can be a deliberate decision.',
      'Define one observable condition that must exist before a simulated trade qualifies.',
      'day',
    ],
    [
      'Confidence',
      'Useful confidence comes from a repeatable process and honest records, not a short run of wins. A good outcome can follow a poor decision, and a careful decision can still lose. Track adherence separately from profits.',
      'You follow every rule and lose one simulated trade. On another, you ignore your limits and win. The second result does not validate the broken rule.',
      'Evaluate the decision using what was known at the time, not only the outcome.',
      'Create separate journal scores for process quality and financial result.',
      'bias',
    ],
    [
      'Discipline',
      'Discipline is the practice of following a considered process, reviewing evidence, and making changes deliberately. It is not stubbornly repeating a failing method. Build routines small enough that you can actually maintain them.',
      'Before a paper trade, you record the idea, invalidation, size, and costs. Afterward, you record the outcome and one lesson. A weekly review looks for repeated mistakes.',
      'A useful routine makes your decisions easier to inspect and improve.',
      'Write a three-step study routine you can repeat next week.',
      'plan',
    ],
  ],
];
export interface Lesson {
  id: string;
  phase: number;
  title: string;
  explanation: string;
  example: string;
  takeaway: string;
  practice: string;
  source: SourceKey;
  minutes: number;
}
export const lessons: Lesson[] = content.flatMap((rows, phase) =>
  rows.map(([title, explanation, example, takeaway, practice, source]) => ({
    id: title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/-$/, ''),
    phase,
    title,
    explanation,
    example,
    takeaway,
    practice,
    source,
    minutes: Math.max(
      2,
      Math.ceil(
        (explanation + ' ' + example + ' ' + takeaway + ' ' + practice).split(/\s+/).length / 140,
      ) + 1,
    ),
  })),
);
export const checkpoints = [
  {
    question: 'What does a displayed last-traded price tell you?',
    options: [
      'The price of a recent completed trade',
      'The guaranteed price of your next order',
      'The asset’s value tomorrow',
    ],
    answer: 0,
    explanation:
      'It records a completed trade. New orders, available quantity, and changing quotes can make your next price different.',
  },
  {
    question:
      'With $100 supporting $1,000 of exposure, what does a 5% adverse move cost before fees?',
    options: ['$5', '$50', '$500'],
    answer: 1,
    explanation: '5% of the $1,000 exposure is $50—half the original $100 capital.',
  },
  {
    question: 'A candle opens at $100 and closes at $105. What does its body represent?',
    options: [
      'Every trade in sequence',
      'The $100–$105 interval between open and close',
      'A guarantee that the next candle rises',
    ],
    answer: 1,
    explanation:
      'The body connects opening and closing prices. Wicks show the interval’s high and low.',
  },
  {
    question: 'Price briefly dips below a common stop level and recovers. What can you conclude?',
    options: [
      'An institution definitely manipulated it',
      'Price traded below the level and recovered',
      'The next trade is guaranteed to win',
    ],
    answer: 1,
    explanation:
      'The price action is observable. A participant’s intention is not established by the wick alone.',
  },
  {
    question: 'What does an RSI reading above 70 guarantee?',
    options: [
      'An immediate price reversal',
      'A profitable short trade',
      'Neither of these outcomes',
    ],
    answer: 2,
    explanation: 'RSI describes momentum. It can stay elevated during a strong trend.',
  },
  {
    question: 'An account loses 20%, falling from $1,000 to $800. What gain restores it?',
    options: ['20%', '25%', '40%'],
    answer: 1,
    explanation: 'The required $200 recovery divided by the remaining $800 is 25%.',
  },
  {
    question: 'Which response best supports a repeatable learning process after a loss?',
    options: [
      'Increase size until you break even',
      'Pause and review the decision against your plan',
      'Copy the next popular trade',
    ],
    answer: 1,
    explanation:
      'A review separates process from outcome. A loss does not make the next opportunity better.',
  },
];
